language: scala

branches:
  only:
  - master
  - mysql # TODO: remove

# Use container-based infrastructure
sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - mysql -e 'CREATE DATABASE somnus;'

script:
  - sbt scalafmtCheckAll ++$TRAVIS_SCALA_VERSION test-ci
